### ISSUE TITLE
[Account linking][OAuth sign in][JWT] Certificate for key id (kid) not found. 

### ISSUE THREAD

**Issue by davidalbertonogueira** [treethought/flask-assistant#129]
Hi @treethought ,

I was trying to perform Account linking to be able to recognize my users, and I made a small demo action based on your samples/account_linking/webhook.py for it.

1) For now I'm attempting Account linking via Google Sign in, but I would like to know if you aim to support authentication with an OAuth server (and not through Google Sign-in).

2) I edited the file with my AOG_CLIENT_ID with my CLIENT_ID obtained by setting up the Account linking in the AOG Console (@ https://console.actions.google.com/u/0/ + Develop + Account Linking). 
However, when launching the web server, and asking the google assistant to talk to my action, the webserver catches an error even before reaching the fulfillment functions for each intent.

From what I gathered, I receive a JWT token during OAuth sign in. I decoded it and in the header, we grab the 'kid' field, which is matched against the keys of the provided certificates, which are the GOOGLE_PUBLIC_KEY you have on flask_assistant/utils.py.

It will then raise the error raise "Certificate for key id {} not found.", with the kid of the token.

This happens at line 222 of https://github.com/googleapis/google-auth-library-python/blob/master/google/auth/jwt.py

How should I proceed?

**Comment by davidalbertonogueira** [comment]
Regarding 2), the problem was the hardcoded GOOGLE_PUBLIC_KEY on flask_assistant/utils.py.

I've fixed that and I now load that dynamically from a Google endpoint. I can offer you a pull request (https://github.com/davidalbertonogueira/flask-assistant ).

**Comment by treethought** [comment]
Hi @davidalbertonogueira thanks for the PR for the public key. I do intend to support authentication via OAuth though I am not sure how soon this will be.

**Comment by tlaskyd** [comment]
Hello @treethought.
Since I use flask_assistant in the project for my bachelor thesis, I would like to ask if the solution from @davidalbertonogueira will ever be implemented in the official library. Now I am forced to use git+https: //github.com/davidalbertonogueira/flask-assistant in requirements.txt and this is not the best solution. (Offical library still does not work.)
Thank you. :)

**Comment by SouravMalliK** [comment]
Looking forward to get a release with this features.

**Comment by treethought** [comment]
thanks for the input and your patience @tlaskyd and @SouravMalliK. I have merged the dynamic fetching of the private key and intend to publish a new release this week. I just need to make some fixes related to dependencies for python 3.5

**Comment by treethought** [comment]
flask-assistant v0.5.0 has now been published to pypi with the dynamic key fetching. please let me know if you encounter any problems after upgrading

**Comment by SouravMalliK** [comment]
Hi thanks for the release. But I'm not getting the response module when I install the 0.5.0 version using pip install. 

```Traceback (most recent call last):
  File "/Users/sourav/source/main.py", line 10, in <module>
    from flask_assistant import Assistant, ask,  profile, sign_in, context_manager, event
  File "/Users/sourav/source/venv/lib/python3.6/site-packages/flask_assistant/__init__.py", line 16, in <module>
    from flask_assistant.core import (
  File "/Users/sourav/source/venv/lib/python3.6/site-packages/flask_assistant/core.py", line 11, in <module>
    from flask_assistant.response import _Response
ModuleNotFoundError: No module named 'flask_assistant.response'```
